USE [master]
GO
/****** Object:  Database [LearnApps]    Script Date: 2017/06/25 15:20:40 ******/
CREATE DATABASE [LearnApps]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'LearnApps', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\LearnApps.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON
( NAME = N'LearnApps_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\LearnApps_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [LearnApps] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LearnApps].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LearnApps] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [LearnApps] SET ANSI_NULLS OFF
GO
ALTER DATABASE [LearnApps] SET ANSI_PADDING OFF
GO
ALTER DATABASE [LearnApps] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [LearnApps] SET ARITHABORT OFF
GO
ALTER DATABASE [LearnApps] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [LearnApps] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [LearnApps] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [LearnApps] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [LearnApps] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [LearnApps] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [LearnApps] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [LearnApps] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [LearnApps] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [LearnApps] SET  DISABLE_BROKER
GO
ALTER DATABASE [LearnApps] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [LearnApps] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [LearnApps] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [LearnApps] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [LearnApps] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [LearnApps] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [LearnApps] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [LearnApps] SET RECOVERY SIMPLE
GO
ALTER DATABASE [LearnApps] SET  MULTI_USER
GO
ALTER DATABASE [LearnApps] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [LearnApps] SET DB_CHAINING OFF
GO
ALTER DATABASE [LearnApps] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [LearnApps] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO
ALTER DATABASE [LearnApps] SET DELAYED_DURABILITY = DISABLED
GO
USE [LearnApps]
GO
/****** Object:  Table [dbo].[MST_Manager]    Script Date: 2017/06/25 15:20:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MST_Manager](
	[ASP_ID] [varchar](8) NOT NULL,
	[ManageUserId] [int] NOT NULL,
 CONSTRAINT [PK_MST_Manager] PRIMARY KEY CLUSTERED
(
	[ASP_ID] ASC,
	[ManageUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MST_Price]    Script Date: 2017/06/25 15:20:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MST_Price](
	[ASP_ID] [varchar](8) NOT NULL,
	[ProductId] [int] NOT NULL,
	[Price] [money] NULL,
 CONSTRAINT [PK_MST_Price] PRIMARY KEY CLUSTERED
(
	[ASP_ID] ASC,
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MST_Product]    Script Date: 2017/06/25 15:20:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MST_Product](
	[ProductId] [int] NOT NULL,
	[ProductName] [varchar](50) NULL,
 CONSTRAINT [PK_MST_Product] PRIMARY KEY CLUSTERED
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderManage]    Script Date: 2017/06/25 15:20:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderManage](
	[SessionId] [varchar](50) NOT NULL,
	[OrderId] [varchar](50) NULL,
	[ProductId] [int] NULL,
	[Price] [money] NULL,
 CONSTRAINT [PK_OrderManage] PRIMARY KEY CLUSTERED
(
	[SessionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [LearnApps] SET  READ_WRITE
GO
